# Playbook: Build and publish docker image to registry
# usage: ansible-playbook publish.yml -e version=0.0.0
#
---
- hosts: 127.0.0.1
  # vars_files:
  #   - version.yml
  # vars:
  #   version: "{{ ver_teonet }}"

  tasks:

  - name: simple-ansibleplaybook 
    debug:
      msg: Your are running 'build and publish teonet docker' example

  - name: build and publish docker image to registry
    shell: |
           cd $HOME/go/src/github.com/kirill-scherba/{{ name }}
           echo Build docker image
           docker build -t {{ name }} -f ./Dockerfile ../.
           echo ""
           docker tag {{ name }} docker.pkg.github.com/kirill-scherba/teonet-go/{{ name }}:{{ version }}
           docker push docker.pkg.github.com/kirill-scherba/teonet-go/{{ name }}:{{ version }}
           echo ""
           docker tag {{ name }} docker.pkg.github.com/kirill-scherba/teonet-go/{{ name }}:latest
           docker push docker.pkg.github.com/kirill-scherba/teonet-go/{{ name }}:latest

    register: out
  - debug: var=out.stdout_lines
